### PR TITLE
delete kahoot completely

### PR DESCRIPTION
**Pull request by shadow01148**
i opened pr on wrong repo

lmao

### CODE REVIEW

**Comment by wotgary** [comment]
State your reason

**Review by garylkz — CHANGES_REQUESTED** [review]
Give a good reason, also 69th PR, expect a parodic review

**Comment by shadow01148** [comment]
> Give a good reason, also 69th PR, expect a parodic review

Has no API and should be replace with Matrix

**Comment by garylkz** [comment]
> > Give a good reason, also 69th PR, expect a parodic review
> 
> Has no API and should be replace with Matrix

Why do you think kahoot lib exist in python?

**Comment by shadow01148** [comment]
reviewer is based and removed
i would like to hear from other reviewer

**Comment by Itzbenz** [comment]
check failed

**Pull request closed without merging**
